version: '3.3'

services:
  mysql:
    container_name: sopcom-mysql
    image: mysql
    restart: on-failure
    ports:
      - "1025:3306"
    networks: 
      - database
    environment:
      MYSQL_DATABASE: sopcom_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: adg6pMtxO
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  
  backend:
    build:
      context: api
    container_name: sopcom-backend
    restart: always
    ports:
      - "1026:80"
    networks: 
      - database

  frontend:
    container_name: sopcom-frontend
    build:
      context: client
    ports:
      - "1027:80"
    networks:
      - http

networks:
  database:
    driver: bridge
  http:
    driver: bridge